<?php include("connection.php");?>
<?php include("error.php");?>
<?php include("circuit_championship.php");?>
<?php include("championship.php");?>
<?php include("circuit.php");?>
<?php include("team.php");?>
<?php include("user.php");?>
<?php include("user_team.php");?>
<?php include("inscription.php");?>
<?php include("game.php");?>
