#!/bin/bash      

#Path del directorio backup que contendra los archivos que contienen el estado del servidor de nuestra aplicación
path="$HOME/pfc-pj-backup" 
path_server="/var/www/racing"
path_src="/var/local/share/racing"

rm -fr $path
mkdir $path

diract=`pwd`

dirtmp=`mktemp -d`

#Comanda para la creacion de un backup de la base de datos del proyecto, mediante la funcion de mysql 'mysqldump'
mysqldump --opt --password=proyecto --user=root pfc > $dirtmp/archivo.sql

#Directorio con los archivos PHP
cp -r $path_server $dirtmp/www_racing

#Directorio con la informacion de los circuitos,
#partidas y archivos para la ejecucion de partidas
cp -r $path_src $dirtmp/racing

#Comanda para comprimir el directorio backup
cd $dirtmp
tar zcvf $path/backup_pfc.tar.gz * 
cd $diract


