#!/bin/bash      

#Path del directorio backup que contendra los archivos que contienen el estado del servidor de nuestra aplicación
path="/home/dvd/Escritorio" 
path_server="/var/www"
path_src="/home/dvd/share"

dirtmp=`mktemp -d`

#Comanda para la creacion de un backup de la base de datos del proyecto, mediante la funcion de mysql 'mysqldump'
mysqldump --opt --password=proyecto --user=root pfc > $dirtmp/archivo.sql

#Directorio con los archivos PHP
cp -r $path/pfc-pj/david/php $dirtmp/php

#Directorio con la configuracion de las rutas
cp -r $path_server/conf $dirtmp/conf

#Directorio con las imagenes 
cp -r $path_server/img $dirtmp/img

#Directorio con la informacion de los circuitos, partidas y archivos para la ejecucion de partidas
mkdir $dirtmp/racing
cp -r /home/dvd/Escritorio/pfc-pj/omer/racing/bin $dirtmp/racing/bin
cp -r /home/dvd/Escritorio/pfc-pj/omer/racing/circuitos $dirtmp/racing/circuits
cp -r $path_src/racing/games $dirtmp/racing/games
cp -r $path_src/racing/pack $dirtmp/racing/pack


#Comanda para comprimir el directorio backup
tar zcvf $path/backup_pfc.tar.gz $dirtmp 


